---

- name: Run web
  hosts: all
  become: true

  tasks:

    - name: customize smsd user
      ansible.builtin.lineinfile:
        dest: "/etc/init.d/gammu-smsd"
        state: present
        regexp: "^USER="
        insertafter: '^# user which will run this daemon'
        line: USER=root

    - name: Start service
      service: name=gammu-smsd state=restarted enabled=yes

    - name: Create named pipe
      command:
        cmd: mkfifo /home/pi/listener
        creates: /home/pi/listener
    
    - name: Copy script
      template: src=lis_crpt.sh.j2 dest=/home/pi/lis_crpt.sh mode=777

    - name: Create Unit file
      template: src=dc_listener.service.j2 dest=/etc/systemd/system/dc_listener.service mode=644
      notify:
        - systemctl daemon-reload
    
    - name: Start service
      service: name=dc_listener.service state=started enabled=yes

    - name: customize /etc/environment
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^CHECK_B="
        line: "CHECK_B={{ check_b }}"

    - name: customize /etc/environment
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^TRAEF_NAME="
        line: "TRAEF_NAME={{ name }}"
    
    - name: git pull
      ansible.builtin.git:
        repo: 'https://github.com/MrGrin93/sms_for_pi.git'
        dest: /home/pi/sms_for_pi
        version: prod

    - name: Ensure docker library is present.
      pip:
        name: docker
        state: present

    - name: Ensure docker-compose library is present.
      pip:
        name: docker-compose
        state: present

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/pi/sms_for_pi
        build: true
      register: output